name: basic_code
channels:
  - defaults
  - conda-forge
dependencies:
  - black=23.11.0
  - flake8=6.1.0
  - jupyter=1.0.0
  - jupyter_client=7.4.9
  - jupyter_console=6.6.3
  - jupyter_core=5.3.0
  - jupyter_server=1.23.4
  - python=3.10.0
  - scikit-learn=1.3.0
  - scipy=1.11.4
  - seaborn=0.12.2
  - pip:
      - matplotlib==3.8.1
      - numpy==1.26.0
      - pandas==2.1.2
      - dython
