name: basic_code
channels:
  - defaults
  - conda-forge
dependencies:
  # - scikit-learn=1.3.0=py310h4ed8f06_1
  # - scipy=1.11.4=py310h309d312_0
  # - seaborn=0.12.2=py310haa95532_0
  - pip:
      # - matplotlib==3.8.1
      # - numpy==1.26.0
      # - pandas==2.1.2
