services:
  app:
    build:
      context: .  # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile
    container_name: fastapi_app
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"  # Map host port 8000 to container port 8000
    depends_on:
      - mongodb  # Wait for MongoDB to start before starting the app
    environment:
      - MONGODB_HOST_NAME=mongodb

  mongodb:
    image: mongo:latest  # Use the official MongoDB image
    container_name: mongodb
    volumes:
      - ./data/articles_content:/data/articles_content  # Bind mount for MongoDB data
    ports:
      - "27017:27017"  # Expose MongoDB port
    command: ["--bind_ip_all"] #["--bind_ip", "127.0.0.1"]